version: '3.8'

services:
  postgres:
    container_name: boilerplate-db-postgres
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: boilerplate
      PGDATA: /data/postgres
    # volumes:
    #   - ./data/postgres:/data/postgres
    # redis:
    #   container_name: boilerbplate-db-redis
    #   image: redis
    #   ports:
    #     - 6379:6379
    #   volumes:
    #     - ./data/redis:/data
